# Generated by Django 3.0.4 on 2020-07-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms_otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='EMAIL_OTP',
        ),
        migrations.DeleteModel(
            name='SMS_OTP',
        ),
    ]
