# Generated by Django 3.0.4 on 2020-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200727_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
