# Generated by Django 3.1 on 2020-08-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200815_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='paid',
        ),
    ]
