# Generated by Django 3.1 on 2020-08-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200817_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
