# Generated by Django 3.0.4 on 2020-08-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
