# Generated by Django 3.1 on 2020-08-24 17:48

import clubs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200808_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_paid', models.CharField(choices=[['unpaid', 'unpaid'], ['pending', 'pending'], ['paid', 'paid']], default='unpaid', max_length=255)),
                ('grand_parent_paid', models.CharField(choices=[['unpaid', 'unpaid'], ['pending', 'pending'], ['paid', 'paid']], default='unpaid', max_length=255)),
                ('parent_document', models.ImageField(blank=True, null=True, upload_to=clubs.models.upload_path)),
                ('grand_parent_document', models.ImageField(blank=True, null=True, upload_to=clubs.models.upload_path)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.club')),
            ],
        ),
        migrations.DeleteModel(
            name='Club1000',
        ),
    ]
