# Generated by Django 3.1 on 2020-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20200824_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpayment',
            name='grand_parent_document',
        ),
        migrations.RemoveField(
            model_name='clubpayment',
            name='parent_document',
        ),
        migrations.AddField(
            model_name='clubpayment',
            name='grandparent_ss_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clubpayment',
            name='parent_ss_url',
            field=models.URLField(blank=True),
        ),
    ]
