# Generated by Django 3.1 on 2020-08-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20200830_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpayment',
            name='both_parent_paid',
            field=models.BooleanField(default=False),
        ),
    ]
