# Generated by Django 3.1 on 2020-08-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_clubpayment_both_parent_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpayment',
            name='both_parent_paid',
        ),
    ]
